INSERT INTO `openUk`.`answers` (`id`, `id_question`, `text`, `correct`) VALUES (NULL, '1', 'Братськ', '1');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('1', 'Брацьк', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('9', 'житньогі́рний', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('9', 'житньогі́рський', '1');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('2', 'ч..орнило, веч..рові, пш..но', '1');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('2', '…рігамі, ст…лева, терм…кружка', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('2', 'м..сяцеві, к…мп’ютер, числ…ва', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('3', 'кашт…н, К…їв, математ…ка', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('3', 'К…шинів, реч…ння, правоп…с ', '1');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('3', 'Брат…слава, ч…слівник, бл…кнот', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('4', 'пробиваєт..ся промін..чик', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('4', 'заход..те до книгозбір..ні', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('4', 'гуцул..ське різ..блення', '1');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('4', 'чотир..ох велет..нів', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('5', 'випещ..ний, долон..чка, удалеч..ні, овоч..сховище', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('5', 'книж..чка, корен..плоди, город..на, б..нтежити', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('5', 'ож..ледь, сив..на, замер..хтіти, л..вада', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('5', 'випл..каний, гус..ниця, защ..друвати, л..ментувати', '0');
INSERT INTO `openUk`.`answers` (`id_question`, `text`, `correct`) VALUES ('5', 'сут..ніти, зат..сатися, горщ..ковий, кл..котіти ', '1');

